"""empty message

Revision ID: 2cbeb3d05cbb
Revises: 
Create Date: 2021-05-17 15:14:45.419154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbeb3d05cbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('twoFALoggedin', sa.Boolean(), nullable=True),
    sa.Column('twoFAKey', sa.String(length=250), nullable=False),
    sa.Column('invite_code', sa.String(length=250), nullable=True),
    sa.Column('email_code', sa.String(length=250), nullable=True),
    sa.Column('apiKey', sa.String(length=255), nullable=True),
    sa.Column('emailConfirmed', sa.Boolean(), nullable=False),
    sa.Column('lastLogin', sa.String(length=30), nullable=True),
    sa.Column('userIP', sa.String(length=30), nullable=True),
    sa.Column('tz', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.Enum('security-agent', 'client', 'security-agency', 'gov-agency'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('security_keys',
    sa.Column('security_key_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('pub_key', sa.String(length=65), nullable=True),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('security_key_id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('pub_key'),
    sa.UniqueConstraint('pub_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_keys')
    op.drop_table('users')
    # ### end Alembic commands ###
