"""empty message

Revision ID: 6d9df64eb89f
Revises: 2cbeb3d05cbb
Create Date: 2021-05-20 01:44:56.871296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d9df64eb89f'
down_revision = '2cbeb3d05cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_award')
    op.add_column('users', sa.Column('sms_code', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('language_app', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('is_phone_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_phone_valid')
    op.drop_column('users', 'language_app')
    op.drop_column('users', 'sms_code')
    op.create_table('request_award',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_bid_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('revoke_reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('revoke_custom_reason', mysql.TEXT(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['request_bid_id'], ['request_bids.request_bid_id'], name='request_award_ibfk_2'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], name='request_award_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='request_award_ibfk_3'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
